:zap:  new account type complete!
added manager account type that can oversee locales

Also added more application contexts to the rest of the flask applications

Still need to fix ImportError: cannot import name 'Locale' from 'app.models' (/Users/pcowe/Desktop/maps4resources/app/models/__init__.py)
02:53:54 worker.1 | ImportError: cannot import name 'Locale' from 'app.models' (/Users/pcowe/Desktop/maps4resources/app/models/__init__.py)